mt5:
  login: 95811163
  password: "8cJi-oAf"
  server: "MetaQuotes-Demo"

symbol: "XAUUSD"
timeframe: "M1"
bars_to_fetch: 3000
poll_interval_sec: 5

zigzag:
  depth: 8
  deviation: 5
  backstep: 3

patterns:
  - ["HL", "HH", "LL", "LH", "LL"]
  - ["HH", "HL", "HH", "LH"]

webhook_url: "https://script.google.com/macros/s/REPLACE_WITH_YOUR_APPS_SCRIPT/exec"
